builds:
  - main: ./cmd/check-memory-usage/main.go
    id: "check-memory-usage"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/check-memory-usage
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - darwin_amd64
      - freebsd_amd64
      - freebsd_386
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

  - main: ./cmd/check-swap-usage/main.go
    id: "check-swap-usage"
    env:
    - CGO_ENABLED=0
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/check-swap-usage
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - darwin_amd64
      - freebsd_amd64
      - freebsd_386
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
